import gspread
from oauth2client.service_account import ServiceAccountCredentials
scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']
creds = ServiceAccountCredentials.from_json_keyfile_name('./client_secret.json', scope)
client = gspread.authorize(creds)

# Make sure you use the right name here.
sheet = client.open("Hackathon Demo").sheet1
#print(sheet)
name=sheet.cell(subject,2).value
data = [
"Graphics And Design",
"Digital Marketing",
"Writing & Translation",
"Video & Animation",
"Music & Audio",
"Programming & Tech",
"Data Science",
"Business",
"Lifestyle",
"All in Graphics & Design",
"Logo Design",
"Brand Style Guides",
"Game Art",
"Graphics for Streamers",
"Business Cards & Stationery",
"Resume Design",
"Illustration",
"Pattern Design",
"Brochure Design",
"Poster Design",
"Flyer Design",
"Book Design",
"Album Cover Design",
"Podcast Cover Art",
"Packaging Design",
"AR Filters & Lenses",
"Storyboards",
"Web & Mobile Design",
"Social Media Design",
"Postcard Design",
"Catalog Design",
"Menu Design",
"Invitation Design",
"Portraits & Caricatures",
"Cartoons & Comics",
"Tattoo Design",
"Signage Design",
"Web Banners",
"Photoshop Editing",
"Architecture & Interior Design",
"Landscape Design",
"Building Information Modeling",
"Character Modeling",
"Industrial & Product Design",
"Trade Booth Design",
"Fashion Design",
"Jewelry Design",
"Presentation Design",
"Email Design",
"Icon Design",
"Infographic Design",
"Car Wraps",
"Vector Tracing",
"Articles & Blog Posts",
"Proofreading & Editing",
"Translation",
"Website Content",
"Product Descriptions",
"Book & eBook Writing",
"Book Editing",
"Resume Writing",
"Brand Voice & Tone",
"UX Writing",
"Email Copy",
"Technical Writing",
"White Papers",
"Sales Copy",
"Social Media Copy",
"Podcast Writing",
"Ad Copy",
"Cover Letters",
"Press Releases",
"Case Studies",
"LinkedIn Profiles",
"Creative Writing",
"Scriptwriting",
"Business Names & Slogans",
"eLearning Content Development",
"Speechwriting",
"Legal Writing",
"Grant Writing",
"Transcripts",
"Research & Summaries",
"All in Video & Animation",
"Whiteboard & Animated Explainers",
"Video Editing",
"Short Video Ads",
"Animated GIFs",
"Logo Animation",
"Intros & Outros",
"Character Animation",
"3D Product Animation",
"Lyric & Music Videos",
"Animation for Kids",
"Animation for Streamers",
"Spokespersons Videos",
"Subtitles & Captions",
"Visual Effects",
"Website Animation",
"eLearning Video Production",
"Article to Video",
"Unboxing Videos",
"Screencasting Videos",
"Slideshow Videos",
"App & Website Previews",
"Drone Videography",
"Book Trailers",
"Real Estate Promos",
"Game Trailers",
"Product Photography",
"Local Photography",
"Other",
"All in Music & Audio",
"Voice Over",
"Mixing & Mastering",
"Producers & Composers",
"Singers & Vocalists",
"Session Musicians",
"Songwriters",
"Beat Making",
"Online Music Lessons",
"Podcast Editing",
"Audiobook Production",
"Audio Ads Production",
"Sound Design",
"Dialogue Editing",
"Music Transcription",
"Vocal Tuning",
"DJ Drops & Tags",
"DJ Mixing",
"Remixing & Mashups",
"Synth Presets",
"Meditation Music",
"Jingles & Intros",
"Market Research",
"Business Plans",
"Customer Care",
"Project Management",
"HR Consulting",
"Legal",
"Financial Consulting",
"Business Consulting",
"Presentations",
"Game Concept Design",
"Flyer Distribution",
"Lead Generation",
"Gaming",
"Online General Education",
"Modeling & Acting",
"Fitness Lessons",
"Dance Lessons",
"Personal Stylists",
"Cooking Lessons",
"Craft Lessons",
"Arts & Crafts",
"Health",
"Family & Genealogy",
"Greeting Cards & Videos",
"Your Message On...",
"Collectibles And NFTS",
"Traveling",
"WordPress",
"Website Builders & CMS",
"Game Development",
"Development for Streamers",
"Web Programming",
"Mobile Apps",
"Desktop Applications",
"Cybersecurity & Data Protection",
"Support & IT",
"Online Coding Lessons",
"Chatbots",
"Convert Files",
"Automated Testing",
"Website Development",
"Databases",
"Data Processing",
"Data Analytics",
"Data Visualization",
"Social Media Advertising",
"Social Media Marketing",
"Search Engine Optimization (SEO)",
"Public Relations",
"Content Marketing",
"Video Marketing",
"Email Marketing",
"Crowdfunding",
"Search Engine Marketing (SEM)",
"Display Advertising",
"Marketing Strategy",
"Web Analytics",
"Influencer Marketing",
"Community Management",
"Local SEO",
"Mobile App Marketing"]
for i in data:
    print(i)